st.markdown("""
    <style>
    .outer-container {
        padding: 10px;
        background-color: #07268b;  /* Farbe der äußeren Ränder */
    }
    .inner-container {
        background-color: white;  /* Farbe des inneren Bereichs */
        padding: 20px;
        border-radius: 5px;
    }
    </style>
""", unsafe_allow_html=True)
