[theme]
primaryColor = "#F63366"
backgroundColor = "#6495ED"  # Haupt-Hintergrundfarbe
secondaryBackgroundColor = "#D1EEEE"  # Hintergrundfarbe für sekundäre Bereiche
textColor = "#262730"
font = "sans serif"
