[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"  # Haupt-Hintergrundfarbe
secondaryBackgroundColor = "#F0F2F6"  # Hintergrundfarbe für sekundäre Bereiche
textColor = "#262730"
font = "sans serif"
