st.markdown(
    """
    <style>
    .reportview-container{
        background.url("https://github.com/maxg0072/CS/blob/patch-2/pexels-mudassir-ali-3970396.jpg");
    }
    </style>
    """,
    unsafe_allow_html=True
    )